# Generated by Django 4.2.6 on 2023-11-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sethub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sethub',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
