# Generated by Django 4.2.6 on 2023-11-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sethub', '0002_sethub_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sethub',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
